name: Nova Vaga
description: Nova Vaga
title: "[Vaga]: "
labels: ["aberta"]
body:
  - type: input
    id: Titulo
    attributes:
      label: Titulo da Vaga
      description: Titulo da Vaga em Aberto
      placeholder: ex. Pessoa Programadora .Net Senior
    validations:
      required: true
  - type: textarea
    id: descricao
    attributes:
      label: Descrição da Vaga
      description: Descrição da Vaga
    validations:
      required: true
  - type: dropdown
    id: tipovaga
    attributes:
      label: Tipo da Vaga
      description: Vaga Presencial ou Remota
      options:
        - 100% presencial
        - 100% remota
        - Parcialmente Remota
    validations:
      required: true
  - type: textarea
    id: requisitos
    attributes:
      label: Requisitos da Vaga
      description: Requisitos da Vaga
    validations:
      required: true
  - type: input
    id: empresa
    attributes:
      label: Nome da Empresa
      description: Informe o nome da Empresa que está disponibilizando a vaga
      placeholder: ex. Acme 
    validations:
      required: true      
      
  - type: input
    id: contact
    attributes:
      label: Email para Contato
      description: informe o e-mail para contato
      placeholder: ex. email@example.com
    validations:
      required: true

  - type: input
    id: salario
    attributes:
      label: Faixa Salarial
      description: Informe a faixa salarial da Vaga
      placeholder: ex. R$ 5.000,00 / mês
    validations:
      required: true   

  - type: dropdown
    id: metodocontratacao
    attributes:
      label: Método de Contratação
      description: Método de Contratação
      options:
        - CLT
        - PJ
        - Cooperado

  - type: textarea
    id: beneficios
    attributes:
      label: Informe os Beneficios
      description: Beneficios
    validations:
      required: true

  - type: input
    id: linkvaga
    attributes:
      label: Link para submissão da Vaga
      description: link para submissão da Vaga em sites externos
      placeholder: ex. https://www.linkedin.com/jobs/collections/recommended/?currentJobId=32131231231231
    validations:
      required: false